### ISSUE TITLE
Add a DAO for posting and getting textTranscripts

### ISSUE THREAD

**Issue by ProEdge2** [Ajinkya-B/Ghost-Busters#1]
- Create a new DAO file for textTranscrips that has its own add, remove, and get functions. These functions can be then called by the controller. 
- It needs a inject function(to first initialize connection with mongoDB)
- Refer to the transcripsDAO (for the inject, getTranscripts, addTranscript) like functions.

**Comment by Ajinkya-B** [comment]
While refactoring the folder structure I made some progress on creating a separate DAO for text transcripts and have pushed those changes to another branch called 2.1-text-transcripts-DAO. I will create a pr shortly to merge it with issue #2.
