### ISSUE TITLE
Refactor UploadTranscript use case

### ISSUE THREAD

**Issue by ProEdge2** [Ajinkya-B/Ghost-Busters#20]
A use case interaction needs to be pulled out from the UploadTranscript use case, the final architecture should be something like the following

Button on the front end that says Upload Transcript (View)
Current project is passed through to the Use case interactor through the controller (controller, Input boundary)
Api call is made to receive transcript data and then is passed to the DAO where it can be saved to the DB (DAO)
The data is saved in the data base (Database)
Success is passed back to the front end through the output boundary to the presenter and then the view (Output, Presenter, View)

**Comment by chwawa** [comment]
Hey Marco, great work so far! I'm not sure if this is the right place to mention this, but I'd recommend creating a TranscriptsDataService (along with an http-common.transcripts) to replace the Axios calls made in UploadTranscripts.js. Image of UploadTranscripts.js for reference:
<img width="739" alt="image" src="https://user-images.githubusercontent.com/98237975/201531345-c8bfadee-6089-47d9-901f-ae3a81dc77d9.png">

(You can view the http-common and services folder in the front-end.)

**Comment by chwawa** [comment]
About my previous comment--since we're not using these functions anymore (Marco reminded me via Discord), we don't need the TranscriptsDataService for now! But for the future, remember to use a data service instead of direct Axios calls in the frontend :)
