### ISSUE TITLE
Create tests for AddProject use case

### ISSUE THREAD

**Issue by chwawa** [Ajinkya-B/Ghost-Busters#29]
- Use JEST to test the that projects get added to the DB

**Comment by Ajinkya-B** [comment]
Hey! Are you planning to create the tests for the front end or the back end for this use case?

**Comment by chwawa** [comment]
Front-end!

**Comment by Ajinkya-B** [comment]
Perfect! I will be working on creating back-end routing tests for the project and transcript data objects.
