### ISSUE TITLE
Create backend tests

### ISSUE THREAD

**Issue by ProEdge2** [Ajinkya-B/Ghost-Busters#49]
Add unit tests for the following files:

coltrolers
DAO's
helpers
Use jest : https://jestjs.io/docs/tutorial-react
https://medium.com/bb-tutorials-and-thoughts/how-to-write-unit-tests-in-nodejs-with-jest-test-library-a201658829c7#:~:text=There%20are%20so%20many%20libraries%20that%20can%20be,the%20box%2C%20config%20free%2C%20on%20most%20JavaScript%20projects.

**Comment by khushiagl** [comment]
![Image](https://user-images.githubusercontent.com/98438613/206625303-901121ed-a786-4b76-9fd8-936a0d85d000.png)

**Comment by Ajinkya-B** [comment]
issue resolved. refer to pr #53 😃
